apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
